// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIxGBSOf8P-s8UPmQo7K-bKNz_0Kktw8',
    appId: '1:833469755633:web:7b77bf13261bd885bab950',
    messagingSenderId: '833469755633',
    projectId: 'trabalho-final-94eca',
    authDomain: 'trabalho-final-94eca.firebaseapp.com',
    storageBucket: 'trabalho-final-94eca.firebasestorage.app',
    measurementId: 'G-RR4CM8RCDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyART9eXs0AAMAYhswSgQ228QZvamJ_Hc4Q',
    appId: '1:833469755633:android:770afcbb9341818fbab950',
    messagingSenderId: '833469755633',
    projectId: 'trabalho-final-94eca',
    storageBucket: 'trabalho-final-94eca.firebasestorage.app',
  );
}
